# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCarrinho():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_carrinho(self):
    # Test name: carrinho
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.itwigs.com.br/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | runScript | window.scrollTo(0,1200) | 
    self.driver.execute_script("window.scrollTo(0,1200)")
    # 4 | click | css=.prod-id-288784405:nth-child(5) .produto-sobrepor | 
    self.driver.find_element(By.CSS_SELECTOR, ".prod-id-288784405:nth-child(5) .produto-sobrepor").click()
    # 5 | mouseOver | css=#splide01-slide01 img | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#splide01-slide01 img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | css=#splide01-slide01 img:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | mouseOver | css=#splide01-slide01 .zoomImg | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#splide01-slide01 .zoomImg")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | mouseOut | css=#splide01-slide01 .zoomImg | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 9 | click | linkText=Comprar | 
    self.driver.find_element(By.LINK_TEXT, "Comprar").click()
    # 10 | click | css=.logo img | 
    self.driver.find_element(By.CSS_SELECTOR, ".logo img").click()
    # 11 | runScript | window.scrollTo(0,613.5999755859375) | 
    self.driver.execute_script("window.scrollTo(0,613.5999755859375)")
    # 12 | mouseOver | css=.prod-id-257819299:nth-child(7) .produto-sobrepor | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".prod-id-257819299:nth-child(7) .produto-sobrepor")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 13 | runScript | window.scrollTo(0,1696) | 
    self.driver.execute_script("window.scrollTo(0,1696)")
    # 14 | click | css=.prod-id-257819299:nth-child(7) .produto-sobrepor | 
    self.driver.find_element(By.CSS_SELECTOR, ".prod-id-257819299:nth-child(7) .produto-sobrepor").click()
    # 15 | mouseOut | css=.prod-id-257819299:nth-child(7) .produto-sobrepor | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 16 | click | linkText=Comprar | 
    self.driver.find_element(By.LINK_TEXT, "Comprar").click()
    # 17 | click | css=.grande | 
    self.driver.find_element(By.CSS_SELECTOR, ".grande").click()
    # 18 | close |  | 
    self.driver.close()
  
